FROM alpine:3.20.2
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
LABEL org.opencontainers.image.authors="Nho Luong <luongutnho@hotmail.com>" \
      org.opencontainers.image.source="https://github.com/nholuongut/kubeconform/" \
      org.opencontainers.image.description="A Kubernetes manifests validation tool" \
      org.opencontainers.image.documentation="https://github.com/nholuongut/kubeconform/" \
      org.opencontainers.image.licenses="Apache License 2.0" \
      org.opencontainers.image.title="kubeconform" \
      org.opencontainers.image.url="https://github.com/nholuongut/kubeconform/"
RUN apk add ca-certificates
COPY kubeconform /
ENTRYPOINT ["/kubeconform"]
